model = "cube_diorama.glb"
light_intensity_scale = 0.005

[camera]
position = [2.5, 2.0, 2.5]
yaw = -135.0
pitch = -20.0
fovy = 45.0
znear = 0.05
zfar = 100.0
speed = 2.0
sensitivity = 1.0

[sun]
direction = [-0.4, -1.0, 1.0]
color = [1.0, 0.98, 0.92]
intensity = 1.5

[grid]
instances_per_row = 10
space_between = 3.0
